package com.example.tutorial.common.datamodel;

public enum KafkaEventType {
  CAMPAIGN_CREATED,
  CAMPAIGN_UPDATED,
  CAMPAIGN_CANCELLED,

  OFFER_CREATED,
  OFFER_CANCELLED,

  CUSTOMER_OFFER_ENROLLED,
  CUSTOMER_OFFER_DISENROLLED,

  MERCHANT_UPDATED

}
