# https://confluent.cloud/
spring.kafka.bootstrap-servers=pkc-921jm.us-east-2.aws.confluent.cloud:9092

# SECURITY via. Username/password (SASL/PLAIN over SSL)
# Additionally, IP Filtering can be added in Confluent Cloud UI to restrict access to specific IPs.
# (NOTE: Other Security options used is mTLS (SSL/TLS), which needs a Client Certificate and the Kafka Cluster CA Certificate.)
spring.kafka.properties.sasl.mechanism=PLAIN
spring.kafka.properties.security.protocol=SASL_SSL
client.id=ccloud-springboot-client-c2b80648-e13d-4749-b9dd-d697c1a99b2e
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username='E3MCEFENJDQNXL7P' password='';

# optimizations
spring.kafka.properties.session.timeout.ms=45000
spring.kafka.producer.value-serializer: org.apache.kafka.common.serialization.StringSerializer


