spring.application.name=springboot-api

# TODO: move to a config server
campaigns.api.url=http://localhost:8080/api/campaigns
offers.api.url=http://localhost:8080/api/offers
merchants.api.url=http://localhost:8080/api/merchants
customers.api.url=http://localhost:8080/api/customers

customer.eligibility.engine.url=http://mock-eligibility-engine/api/eligibility