%%{ init: { "flowchart": { "htmlLabels": true, "wrappingWidth": 500 } } }%%
flowchart TD

%% %%%%%%%%%%%%%%%%%%%%%%%%%%% %%
%% Campaign Write Microservice %%
%% %%%%%%%%%%%%%%%%%%%%%%%%%%% %%
  POSTMAN["POST /campaigns
  <div style='text-align: left'>
{
#emsp; name: 'Summer Savings Blast',
#emsp; description: 'Enjoy huge discounts...',
#emsp; status: 'PLANNED',
#emsp; start_date: '2025-08-01T00:00:00',
#emsp; end_date: '2025-09-30T23:59:59',
#emsp; budget: 10000
}
</div>
"]:::external

subgraph Campaign_Write_Microservice
style Campaign_Write_Microservice fill:#FFF9C4,stroke:#333,stroke-width:1px
CCC["CampaignCommandController<br> - createCampaign()"]:::controller
CCS["CampaignCommandService<br> - createCampaign()
<div style='text-align:left; font-style: italic;'>
<div style='background-color:rgb(252, 251, 240); width:300px;'>
basedto(campaign).json
{
#emsp; <font color=orange>id</font>,
#emsp; ...,
#emsp; data: {
#emsp;#emsp; name: 'Summer Savings Blast',
#emsp;#emsp; description: 'Enjoy huge discounts...',
#emsp;#emsp; status: 'PLANNED',
#emsp;#emsp; start_date: '2025-08-01T00:00:00',
#emsp;#emsp; end_date: '2025-09-30T23:59:59',
#emsp;#emsp; budget: 10000
#emsp; }
}<br>
</div>
CREATE CAMPAIGN
</div>
"]:::service

CCR["CampaignCommandRepository<br> - save()"]:::repository
CEP["CampaignEventPublisher<br> - publishCreateCampaignEvent()"]:::event
end

COUCHBASE_CAMPAIGN_CMD[("Couchbase DB<br>(bucket: campaign)")]:::db

KAFKA_CC[["kafka topic: CAMPAIGN_CREATED
<div style='text-align:left; background-color:#fcf3f0; width:300px;'>
event(campaignevent).json
{
#emsp; <font color=red><b>id</b>:''</font>,
#emsp; status:'PLANNED',
#emsp; start_date:'2025-08-01T00:00:00',
#emsp; end_date:'2025-09-30T23:59:59',
#emsp; budget:10000
}
</div>
"]]:::kafka

%% Flow Steps (Main Command Flow)
POSTMAN -->|1: forward json body| CCC
CCC -->|2: delegate to service| CCS
CCS -->|3: save data model| CCR
CCR -->|4: write to DB| COUCHBASE_CAMPAIGN_CMD
CCS -->|5: publish event| CEP
CEP -->|6: send to kafka topic| KAFKA_CC



%% %%%%%%% %%
%% Styling %%
%% %%%%%%% %%
classDef controller fill:#AED581,stroke:#33691E,stroke-width:1px;
classDef service fill:#FFF3E0,stroke:#F57C00,stroke-width:1px;
classDef repository fill:#E0F2F1,stroke:#00796B,stroke-width:1px;
classDef util fill:#E1BEE7,stroke:#6A1B9A,stroke-width:1px;
classDef event fill:#F8BBD0,stroke:#AD1457,stroke-width:1px,stroke-dasharray: 5 5;
classDef subscriber fill:#EDE7F6,stroke:#512DA8,stroke-width:1px;
classDef external fill:#FFFFFF,stroke:#000,stroke-width:1px,stroke-dasharray: 5 5;
classDef kafka fill:#fcf3f0,stroke:red,stroke-width:1px,stroke-dasharray: 5 5;
classDef db fill:#FFFFFF,stroke:#000,stroke-width:1px,stroke-dasharray: 5 5;
