%%{ init: { "flowchart": { "htmlLabels": true, "wrappingWidth": 500 } } }%%
flowchart TD

%% %%%%%%%%%%%%%%%%%%%%%%%%%%%% %%
%% Campaign Write Microservice  %%
%% %%%%%%%%%%%%%%%%%%%%%%%%%%%% %%
POSTMAN["PUT /campaigns/cancel/{<font color=orange><b>id</b></font>}
  <div style='text-align: left'>
    {
      #emsp; <font color=orange><b>cancellation_reason</b></font>: 'policy_violation',
      #emsp; <font color=orange><b>cancelled_by:</b></font> 'ops_user'
    }
  </div>
"]:::external

subgraph Campaign_Write_Microservice
style Campaign_Write_Microservice fill:#FFF9C4,stroke:#333,stroke-width:1px
  CCC["CampaignCommandController<br> - cancelCampaign()"]:::controller
  CCS["CampaignCommandService<br> - cancelCampaign()
    <div style='text-align:left; font-style: italic;'>
      <div style='background-color:rgb(252, 251, 240); width:350px;'>
        basedto(campaign).json
        {
          #emsp; <font color=orange><b>id</b></font>,
          #emsp; ...,
          #emsp; <font color=orange><b> updated_by</b>(cancelled_by)</font>: 'ops_user',
          #emsp; data: {
          #emsp;#emsp; <font color=blue><b>status</b></font>: 'CANCELLED',
          #emsp;#emsp; <font color=orange><b>cancellation_reason</b></font>: 'policy_violation'
          #emsp; }
        }<br>
      </div>
      CANCEL CAMPAIGN
      - fetch the campaign by <font color=orange><b>id</b></font> from the REST API (using @ApiUtils).<br>
      - then set the <font color=blue><b>status</b>=CANCELLED</font> and the <font color=orange><b>cancellation_reason</b></font>.
    </div>
  "]:::service

  CCR["CampaignCommandRepository<br> - save()"]:::repository
  CEP["CampaignEventPublisher<br> - publishCancelCampaignEvent()"]:::event
end

COUCHBASE_CAMPAIGN_CMD[("Couchbase DB<br>(bucket: campaign)")]:::db

KAFKA_CC[["kafka topic: CAMPAIGN_CANCELLED
  <div style='text-align:left; background-color:#fcf3f0; width:180px;'>
    event(campaignevent).json
    {
      #emsp; <font color=red><b>id</b>:''</font>
    }
  </div>
"]]:::kafka

%% Flow Steps (Main Command Flow)
POSTMAN -->|1: forward json body| CCC
CCC -->|2: delegate to service| CCS
CCS -->|3: save data model| CCR
CCR -->|4: write to DB| COUCHBASE_CAMPAIGN_CMD
CCS -->|5: publish event| CEP
CEP -->|6: send to kafka topic| KAFKA_CC



%% %%%%%%%%%%%%%%%%%%%%%%%% %%
%% Offer Write Microservice %%
%% %%%%%%%%%%%%%%%%%%%%%%%% %%
subgraph Offer_Write_Microservice
style Offer_Write_Microservice fill:#F1F8E9,stroke:#689F38,stroke-width:1px
  OCES["CampaignEventSubscriber<br> - subscribeCancelCampaignEvent()"]:::subscriber

  OCS["OfferCommandService<br> - cancelOffers()
    <div style='text-align:left; font-style: italic;'>
      <div style='background-color:rgb(252, 251, 240); width:300px;'>
        basedto(offer).json
        {
          #emsp; ...,
          #emsp; data: {
          #emsp;#emsp; <font color=green><b>status</b></font>: 'CANCELLED',
          #emsp; }
        }<br>
      </div>
      CANCEL OFFERS (by campaign)
      - fetch the offers by <font color=red><b>campaign_id (id)</b></font> from the REST API (using @ApiUtils).<br>
      - set <font color=green><b>status</b>=CANCELLED</font>.
    </div>
  "]:::service

  OEP["OfferEventPublisher<br> - publishCancelOfferEvent()"]:::event
end

COUCHBASE_OFFER_SUB[("Couchbase DB<br>(bucket: offer)")]:::db

KAFKA_OC[["kafka topic: OFFER_CANCELLED
  <div style='text-align:left; background-color:#fcf3f0; width:180px;'>
    event(offerevent).json
    {
      #emsp; <font color=red><b>id</b>:''</font>,
      #emsp; <font color=orange><b>campaign_id</b>:''</font>,
      #emsp; <font color=orange><b>merchant_id</b>:''</font>
    }
  </div>
"]]:::kafka

%% Flow Steps (Offer Write Flow)
KAFKA_CC --> OCES
OCES -->|1: delegate to service| OCS
OCS -->|2: update data model| COUCHBASE_OFFER_SUB
OCS -->|3: publish event| OEP
OEP -->|4: send to kafka topic| KAFKA_OC



%% %%%%%%%%%%%%%%%%%%%%%%%%%%% %%
%% Merchant Write Microservice %%
%% %%%%%%%%%%%%%%%%%%%%%%%%%%% %%
subgraph Merchant_Write_Microservice
style Merchant_Write_Microservice fill:#F1F8E9,stroke:#689F38,stroke-width:1px
  MES["OfferEventSubscriber<br> - subscribeOfferCancelledEvent()"]:::subscriber

  MC["MerchantCommandService<br> - removeFromActiveOffers()
    <div style='text-align:left; font-style: italic;'>
      <div style='background-color:rgb(252, 251, 240); width:300px;'>
        basedto(merchant).json
        {
        #emsp; ...,
        #emsp; data: {
        #emsp;#emsp; <font color=olive><b>active_offers</b></font>: [
        #emsp;#emsp;#emsp;#emsp; <font color=red><s>id</s></font>
        #emsp;#emsp; ]
        #emsp; }
        }<br>
      </div>
      REMOVE OFFER
      - fetch the merchant by <font color=orange><b>merchant_id (id)</b></font> from the REST API (using @ApiUtils).<br>
      - remove the offer <font color=red><b>id</b></font> from the <font color=olive><b>active_offers</b></font> list.
    </div>
  "]:::service
end

COUCHBASE_MERCHANT_SUB[("Couchbase DB<br>(bucket: merchant)")]:::db

%% Flow Steps (Merchant Write Flow)
KAFKA_OC --> MES
MES -->|1: delegate to service| MC
MC -->|2: update data model| COUCHBASE_MERCHANT_SUB



%% %%%%%%%%%%%%%%%%%%%%%%%%%%% %%
%% Customer Write Microservice %%
%% %%%%%%%%%%%%%%%%%%%%%%%%%%% %%
subgraph Customer_Write_Microservice
style Customer_Write_Microservice fill:#FCE4EC,stroke:#C2185B,stroke-width:1px
  CES["OfferEventSubscriber<br> - subscribeOfferCancelledEvent()"]:::subscriber

  CC["CustomerCommandService<br> - removeFromEnrolledOffers()</b>
    <div style='text-align:left; font-style: italic;'>
      <div style='background-color:rgb(252, 251, 240); width:300px;'>
        basedto(customer).json
        {
        #emsp; ...,
        #emsp; data: {
        #emsp;#emsp; <font color=green><b>enrolled_offers</b></font>: [
        #emsp;#emsp;#emsp;#emsp; <font color=red><s>id</s></font>
        #emsp;#emsp; ]
        #emsp; }
        }<br>
      </div>
      REMOVE OFFER
      - fetch all the customers having this offer <font color=red><b>id</b></font> from the REST API (using @ApiUtils).<br>
      - remove the offer <font color=red><b>id</b></font> from the <font color=green><b>enrolled_offers</b></font> list.
    </div>
  "]:::service

  COEP["CustomerOfferEventPublisher<br> - publishOfferDisenrollmentEvent()"]:::event
end

COUCHBASE_CUSTOMER_SUB[("Couchbase DB<br>(bucket: customer)")]:::db

KAFKA_COD[["kafka topic: CUSTOMER_OFFER_DISENROLLED
  <div style='text-align:left; background-color:#fcf3f0; width:180px;'>
    event(offerdisenrollmentevent).json
    {
      #emsp; <font color=red><b>offerId</b>:''</font>,
      #emsp; <font color=orange><b>customerIds</b></font>:[
      #emsp;]
    }
  </div>
"]]:::kafka

%% Flow Steps (Customer Write Flow)
KAFKA_OC --> CES
CES -->|1: delegate to service| CC
CC -->|2: update data model| COUCHBASE_CUSTOMER_SUB
CC -->|3: publish event| COEP
COEP -->|4: send to kafka topic| KAFKA_COD



%% %%%%%%%%%%%%%%%%%%%%%%%%%%% %%
%% Campaign Write Microservice %%
%% %%%%%%%%%%%%%%%%%%%%%%%%%%% %%
subgraph Campaign_Write_Microservice_Bookkeeping
style Campaign_Write_Microservice_Bookkeeping fill:#BBDEFB,stroke:#1976D2,stroke-width:1px
  CAS["OfferEventSubscriber<br> - subscribeOfferCancelledEvent()"]:::subscriber

  CBS["CampaignCommandService<br> - removeFromLinkedOffers()
    <div style='text-align:left; font-style:italic;'>
      <div style='background-color:rgb(252, 251, 240); width:300px;'>
        basedto(campaign).json
        {
        #emsp; ...,
        #emsp; data: {
        #emsp;#emsp; <font color=navy><b>linked_offers</b></font>: [
        #emsp;#emsp;#emsp;#emsp; <font color=red><s>id</s></font>
        #emsp;#emsp; ]
        #emsp; }
        }<br>
      </div>
      REMOVE OFFER
      - fetch the campaign by <font color=orange><b>campaign_id (id)</b></font> from the REST API (using @ApiUtils).<br>
      - remove the offer <font color=red><b>id</b></font> from the <font color=olive><b>linked_offers</b></font> list.
    </div>
  "]:::service
end

COUCHBASE_CAMPAIGN_BK[("Couchbase DB<br>(bucket: campaign)")]:::db

%% Flow Steps (Campaign Book-keeping Flow)
KAFKA_OC --> CAS
CAS -->|1: delegate to service| CBS
CBS -->|2: update data model| COUCHBASE_CAMPAIGN_BK



%% %%%%%%% %%
%% Styling %%
%% %%%%%%% %%
classDef controller fill:#AED581,stroke:#33691E,stroke-width:1px;
classDef service fill:#FFF3E0,stroke:#F57C00,stroke-width:1px;
classDef repository fill:#E0F2F1,stroke:#00796B,stroke-width:1px;
classDef util fill:#E1BEE7,stroke:#6A1B9A,stroke-width:1px;
classDef event fill:#F8BBD0,stroke:#AD1457,stroke-width:1px,stroke-dasharray: 5 5;
classDef subscriber fill:#EDE7F6,stroke:#512DA8,stroke-width:1px;
classDef external fill:#FFFFFF,stroke:#000,stroke-width:1px,stroke-dasharray: 5 5;
classDef kafka fill:#fcf3f0,stroke:red,stroke-width:1px,stroke-dasharray: 5 5;
classDef db fill:#FFFFFF,stroke:#000,stroke-width:1px,stroke-dasharray: 5 5;
