%%{ init: { "flowchart": { "htmlLabels": true, "wrappingWidth": 500 } } }%%
flowchart TD

%% %%%%%%%%%%%%%%%%%%%%%%%% %%
%% Offer Write Microservice %%
%% %%%%%%%%%%%%%%%%%%%%%%%% %%
POSTMAN["POST /offers
  <div style='text-align: left'>
    {
      #emsp; name: '',
      #emsp; description: '',
      #emsp; status: 'ACTIVE',
      #emsp; type: 'DISCOUNT',
      #emsp; <font color=orange><b> discount_amount</b></font>: 100,
      #emsp; currency: 'USD',
      #emsp; valid_from: '2025-07-15T00:00:00',
      #emsp; valid_to: '2025-08-07T00:00:00',
      #emsp; segment_criteria: 'GOLD',
      #emsp; <font color=orange><b>campaign_id</b></font>: '',
      #emsp; <font color=orange><b>merchant_id</b></font>: ''
    }
  </div>
"]:::external

subgraph Offer_Write_Microservice
style Offer_Write_Microservice fill:#FFF9C4,stroke:#333,stroke-width:1px
  OCC["OfferCommandController<br> - createOffer()"]:::controller
  OCS["OfferCommandService<br> - createOffer()"]:::service

  CV["CampaignValidation<br> - validateCampaign()
    <div style='text-align:left; font-style: italic;'>
      <div style='background-color:rgb(252, 251, 240); width:300px;'>
        basedto(campaign).json
        {
          #emsp; <font color=orange>id</font>,
          #emsp; ...,
          #emsp; data: {
          #emsp;#emsp; <font color=blue><b>status</b></font>: 'PAUSED',
          #emsp;#emsp; <font color=blue><b>end_date</b></font>: '2025-08-12T00:00:00'
          #emsp; }
        }<br>
      </div>
      VALIDATE CAMPAIGN
      - first checks if the <font color=orange><b>campaign_id (id)</b> EXISTS</font> in the Redis Cache or gets it from the REST API (using @CacheUtils).<br>
      - if found, it validates the campaign <font color=blue><b>status</b>=ACTIVE and <b>end_date</b> NOT PASSED</font>.<br>
      - else, throw RequestValidationException if validations fails.
    </div>
  "]:::service

  MV["MerchantValidation<br> - validateMerchant()
    <div style='text-align:left; font-style: italic;'>
      <div style='background-color:rgb(252, 251, 240); width:300px;'>
        basedto(merchant).json
        {
          #emsp; <font color=orange>id</font>,
          #emsp; ...
        }<br>
      </div>
      VALIDATE MERCHANT
      - first checks if the <font color=orange><b>merchant_id (id)</b> EXISTS</font> in the Redis Cache or gets it from the REST API (using @CacheUtils).<br>
      - else, throw RequestValidationException.
    </div>
  "]:::service

  OV["OfferValidation<br> - validateCampaignBudgetNotExceeded()
    <div style='text-align:left; font-style: italic;'>
      <div style='background-color:rgb(252, 251, 240); width:300px;'>
        basedto(campaign).json
        {
        #emsp; ...,
        #emsp; data: {
        #emsp;#emsp; <font color=blue><b>budget</b></font>: 1000
        #emsp; }
        }<br>
      </div>
      VALIDATE CAMPAIGN BUDGET
      - fetch the campaign's <font color=blue><b>budget</b></font> from the Redis Cache or gets it from the REST API (using @CacheUtils).<br>
      - fetch all offers associated for the specified <font color=orange><b>campaign_id</b></font> (using @ApiUtils) and then SUM their <font color=orange><b>discount_amount</b></font> i.e. <font size=1.5em>[{discount_amout=100}, {[{discount_amout=500}, ..].</font><br>
      - finally, compare the offer's TOTAL discount_amount with the campaign's budget and throws RequestValidationException if exceeded.
    </div>
  "]:::service

  OCR["OfferCommandRepository<br> - save()"]:::repository
  OEP["OfferEventPublisher<br> - publishCreateOfferEvent()"]:::event
end

COUCHBASE_OFFER[("Couchbase DB<br>(bucket: offer)")]:::external

KAFKA1[["kafka topic: OFFER_CREATED
  <div style='text-align:left; background-color:#fcf3f0; width:180px;'>
    event(offerevent).json
    {
      #emsp; <font color=red><b>id</b>:''</font>,
      #emsp; <font color=orange><b>campaign_id</b>:''</font>,
      #emsp; <font color=orange><b>merchant_id</b>:''</font>,
      #emsp; ...
    }
  </div>
"]]:::kafka

%% Flow Steps (Main Command Flow)
POSTMAN -->|1: forward json body| OCC
OCC -->|2: delegate to service| OCS
OCS -->|3: validate: campaign| CV
OCS -->|4: validate: merchant| MV
OCS -->|5: validate: check budget| OV
OCS -->|6: save data model| OCR
OCR -->|7: write to DB| COUCHBASE_OFFER
OCS -->|8: publish event| OEP
OEP -->|9: send to kafka topic| KAFKA1



%% %%%%%%%%%%%%%%%%%%%%%%%%%%% %%
%% Merchant Write Microservice %%
%% %%%%%%%%%%%%%%%%%%%%%%%%%%% %%
subgraph Merchant_Write_Microservice
style Merchant_Write_Microservice fill:#F1F8E9,stroke:#689F38,stroke-width:1px
  MES["OfferEventSubscriber<br> - subscribeCreateOfferEvent()"]:::subscriber

  MC["MerchantCommandService<br> - linkOfferToMerchant()
    <div style='text-align:left; font-style: italic;'>
      <div style='background-color:rgb(252, 251, 240); width:300px;'>
        basedto(merchant).json
        {
        #emsp; ...,
        #emsp; data: {
        #emsp;#emsp; <font color=olive><b>active_offers</b></font>: [
        #emsp;#emsp; ]
        #emsp; }
        }<br>
      </div>
      LINK OFFER
      - fetch the merchant for the <font color=orange><b>merchant_id</b></font> from the REST API (using @ApiUtils)<br>
      - add the new <font color=red>offer <b>id</b></font> in the <font color=olive><b>active_offers</b></font> list of the merchant.
    </div>
  "]:::service
end

COUCHBASE_MERCHANT[("Couchbase DB<br>(bucket: merchant)")]:::db

%% Flow Steps (Merchant Write Flow)
KAFKA1 --> MES
MES -->|1: delegate to service| MC
MC -->|2: update data model| COUCHBASE_MERCHANT


%% %%%%%%%%%%%%%%%%%%%%%%%%%%% %%
%% Customer Write Microservice %%
%% %%%%%%%%%%%%%%%%%%%%%%%%%%% %%
subgraph Customer_Write_Microservice
style Customer_Write_Microservice fill:#FCE4EC,stroke:#C2185B,stroke-width:1px
  CES["OfferEventSubscriber<br> - subscribeCreateOfferEvent()"]:::subscriber

  CC["CustomerCommandService<br> - assignOfferToCustomer()</b>
    <div style='text-align:left; font-style: italic;'>
      <div style='background-color:rgb(252, 251, 240); width:300px;'>
        basedto(customer).json
        {
        #emsp; ...,
        #emsp; data: {
        #emsp;#emsp; <font color=green><b>enrolled_offer_ids</b></font>: [
        #emsp;#emsp; ]
        #emsp; }
        }<br>
      </div>
      ASSIGN OFFER
      - fetch ALL customers from the REST API (using @ApiUtils)<br>
      - pass those customers to the @CustomerEligibilityEngineClient an checks their eligibility.<br>
      - if eligible, then enroll them by adding the new <font color=red>offer <b>id</b></font> to the <font color=green><b>enrolled_offer_ids</b></font>.
    </div>
  "]:::service

  CEP["CustomerOfferEventPublisher<br> - publishOfferAssignedEvent()"]:::event
end

COUCHBASE_CUSTOMER[("Couchbase DB<br>(bucket: customer)")]:::db
KAFKA2[["kafka topic: OFFER_ASSIGNED"]]:::kafka

%% Flow Steps (Customer Write Flow)
KAFKA1 --> CES
CES -->|1: delegate to service| CC
CC -->|2: update data model| COUCHBASE_CUSTOMER
CC -->|3: publish event| CEP
CEP -->|4: send to kafka topic| KAFKA2


%% %%%%%%%%%%%%%%%%%%%%%%%%%%% %%
%% Campaign Write Microservice %%
%% %%%%%%%%%%%%%%%%%%%%%%%%%%% %%
subgraph Campaign_Write_Microservice
style Campaign_Write_Microservice fill:#BBDEFB,stroke:#1976D2,stroke-width:1px
  CAS["OfferEventSubscriber<br> - subscribeCreateOfferEvent()"]:::subscriber

  CCS["CampaignCommandService<br> - linkOfferToCampaign()
    <div style='text-align:left; font-style:italic;'>
      <div style='background-color:rgb(252, 251, 240); width:300px;'>
        basedto(campaign).json
        {
        #emsp; ...,
        #emsp; data: {
        #emsp;#emsp; <font color=navy><b>offer_ids</b></font>: [
        #emsp;#emsp; ]
        #emsp; }
        }<br>
      </div>
      LINK OFFER
      - fetch the campaign for the <font color=orange><b>campaign_id</b></font> from the REST API (using @ApiUtils)<br>
      - add the new <font color=red>offer <b>id</b></font> in the <font color=navy><b>offer_ids</b></font> list of the merchant.
    </div>
  "]:::service
end

COUCHBASE_CAMPAIGN[("Couchbase DB<br>(bucket: campaign)")]:::db

%% Flow Steps (Campaign Write Flow)
KAFKA1 --> CAS
CAS -->|1: delegate to service| CCS
CCS -->|2: update data model| COUCHBASE_CAMPAIGN


%% %%%%%%% %%
%% Styling %%
%% %%%%%%% %%
classDef controller fill:#AED581,stroke:#33691E,stroke-width:1px;
classDef service fill:#FFF3E0,stroke:#F57C00,stroke-width:1px;
classDef repository fill:#E0F2F1,stroke:#00796B,stroke-width:1px;
classDef util fill:#E1BEE7,stroke:#6A1B9A,stroke-width:1px;
classDef event fill:#F8BBD0,stroke:#AD1457,stroke-width:1px,stroke-dasharray: 5 5;
classDef subscriber fill:#EDE7F6,stroke:#512DA8,stroke-width:1px;
classDef external fill:#FFFFFF,stroke:#000,stroke-width:1px,stroke-dasharray: 5 5;
classDef kafka fill:#fcf3f0,stroke:red,stroke-width:1px,stroke-dasharray: 5 5;
classDef db fill:#FFFFFF,stroke:#000,stroke-width:1px,stroke-dasharray: 5 5;

