package com.example.tutorial.common.dto;

public enum KafkaEventType {
  CAMPAIGN_CREATED,
  CAMPAIGN_UPDATED,
  CAMPAIGN_CANCELLED,

  OFFER_CREATED,
  OFFER_CANCELLED,

  CUSTOMER_OFFER_ASSIGNED,
  CUSTOMER_OFFER_UNASSIGNED,

  MERCHANT_UPDATED

}
